### ISSUE TITLE
'docker-compose up -d' not working

### ISSUE THREAD

**Issue by UnsignedInt8** [enKryptIO/ethvm-dev-kit#1]
* **I'm submitting a ...**
    - [ ] bug report

* **Bug Report**
```
ethvm-dev-kit git:(master) $> docker-compose up -d

ERROR: Top level object in './docker-compose.yaml' needs to be an object not '<class 'NoneType'>'.
```

I checked the docker-compose.yaml, but it's empty.

**Comment by aldoborrero** [comment]
Yeah, I commited all the project files but with the exception of the docker-compose file till is finished. I'm still working on it (during this week I'll provide it).

Thanks

**Comment by UnsignedInt8** [comment]
Thanks so much.

**Comment by aldoborrero** [comment]
@UnsignedInt8 updated the documentation and uploaded the docker-compose file!

**Comment by aldoborrero** [comment]
Feel free to open a new issue if something bad appears (I'm closing this one)

**Comment by UnsignedInt8** [comment]
Thanks a lot! 👍
