### ISSUE TITLE
Network web declared as external, but could not be found.

### ISSUE THREAD

**Issue by UnsignedInt8** [enKryptIO/ethvm-dev-kit#2]
* **I'm submitting a ...**
    - [ ] bug report

* **Bug Report**
Hi, when I ran `docker-compose up -d` in the terminal, an error message was printed out.

```
ethvm-dev-kit git:(master) > docker-compose up -d
ERROR: Network web declared as external, but could not be found. Please create the network manually using `docker network create web` and try again.
```

So, how do I fix it?

**Comment by aldoborrero** [comment]
@UnsignedInt8 this is not a bug. Error message says it all. Execute the following on the shell:

`$ docker network create web`

Keep in mind that you're going to use a lot docker and docker-compose, so having knowledge of these tools is crucial.

**Comment by UnsignedInt8** [comment]
Thanks, that works!

**Comment by aldoborrero** [comment]
Keep in mind that we're doing heavy refactoring in the server code and other parts (so expect also to not to work properly yet)
